version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.451
- serviceName: edge.testpackage1.integrations:d1
  packages:
  - name: EdgeTestPackage1
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.0.0.0.451
packages:
- name: EdgeTestPackage1
  gitServerName: testServer1
  gitUrl: https://github.com/PoojaAnandGit/EdgeTestPackage1
  gitUsername: PoojaAnandGit
  gitToken: edge.scaffolding.EdgeTestPackage1.testServer1.gitToken
  gitBranch: main
